export interface ShopItem {
  id: string;
  name: string;
  description: string;
  cost: number;
  category: 'body' | 'hair' | 'eyes' | 'outfit' | 'home' | 'vehicle' | 'companion';
  emoji: string;
  accentColor: string;
}

export const SHOP_ITEMS: ShopItem[] = [
  // ── BODIES (Görünüşler / Tenler) ── 20 Items
  { id: 'default_body', name: 'Normal Habitus', description: 'Klasik sevimli yeşil piksel Habitus.', cost: 0, category: 'body', emoji: '👾', accentColor: '#10b981' },
  { id: 'cyborg_body', name: 'Siber Habitus', description: 'Metalik gri parçalara sahip yarı robot gövde.', cost: 30, category: 'body', emoji: '🤖', accentColor: '#3b82f6' },
  { id: 'golden_body', name: 'Altın Habitus', description: 'Saf altından dökülmüş, göz kamaştıran elit gövde!', cost: 30, category: 'body', emoji: '👑', accentColor: '#eab308' },
  { id: 'phantom_body', name: 'Hayalet Gövde', description: 'Karanlıkta mor ışıklar saçan yarı saydam ruhani görünüş.', cost: 30, category: 'body', emoji: '👻', accentColor: '#a855f7' },
  { id: 'fire_body', name: 'Alev Gövdesi', description: 'Ateş ve lav parçacıkları saçan volkanik piksel gövde.', cost: 30, category: 'body', emoji: '🔥', accentColor: '#f97316' },
  { id: 'ice_body', name: 'Buz Gövdesi', description: 'Cam gibi dondurucu buz kristallerinden oluşan gövde.', cost: 30, category: 'body', emoji: '❄️', accentColor: '#38bdf8' },
  { id: 'alien_body', name: 'Uzaylı Gövdesi', description: 'Galaksiler ötesinden gelen zümrüt yeşili gizemli gövde.', cost: 150, category: 'body', emoji: '👽', accentColor: '#22c55e' },
  { id: 'shadow_body', name: 'Gölge Gövdesi', description: 'Karanlıktan doğan, kırmızı gözlü gizemli gölge.', cost: 150, category: 'body', emoji: '🌑', accentColor: '#475569' },
  { id: 'candy_pink_body', name: 'Pembe Şeker', description: 'Şeker pembesi son derece tatlı ve canlı piksel gövde.', cost: 150, category: 'body', emoji: '🍬', accentColor: '#ec4899' },
  { id: 'neon_cyber_body', name: 'Neon Grid Gövde', description: 'Mor zemin üzerinde siber siyan ızgara hatları.', cost: 150, category: 'body', emoji: '🌐', accentColor: '#06b6d4' },
  { id: 'wooden_puppet_body', name: 'Tahta Kukla', description: 'Otantik ahşap dokulu retro kukla gövdesi.', cost: 150, category: 'body', emoji: '🪵', accentColor: '#b45309' },
  { id: 'poison_slime_body', name: 'Zehir Slime', description: 'Köpüren asidik zehir yeşili gövde.', cost: 500, category: 'body', emoji: '🧪', accentColor: '#84cc16' },
  { id: 'galaxy_cosmic_body', name: 'Kozmik Galaksi', description: 'Yıldız nebula desenli büyüleyici derin uzay gövdesi.', cost: 500, category: 'body', emoji: '🌌', accentColor: '#6366f1' },
  { id: 'magma_lava_body', name: 'Magma Gövdesi', description: 'Çatlaklarından canlı kırmızı lavlar sızan siyah kaya.', cost: 500, category: 'body', emoji: '🌋', accentColor: '#dc2626' },
  { id: 'hologram_blue_body', name: 'Mavi Hologram', description: 'Dikey çizgi taranmalı siber hologram görünüşü.', cost: 500, category: 'body', emoji: '📡', accentColor: '#0284c7' },
  { id: 'bronze_warrior_body', name: 'Bronz Zırhlı', description: 'Eskitme bronz metalik piksel gövde.', cost: 500, category: 'body', emoji: '🥉', accentColor: '#d97706' },
  { id: 'diamond_crystal_body', name: 'Elmas Kristal', description: 'Göz kamaştıran mavi elmas parlaklığı!', cost: 800, category: 'body', emoji: '💎', accentColor: '#67e8f9' },
  { id: 'steampunk_brass_body', name: 'Pirinç Steampunk', description: 'Çarklı ve saat düzenekli pirinç metal gövde.', cost: 800, category: 'body', emoji: '⚙️', accentColor: '#ca8a04' },
  { id: 'pastel_lavender_body', name: 'Lavanta Pastel', description: 'Huzur veren tatlı lavanta moru gövde.', cost: 800, category: 'body', emoji: '🪻', accentColor: '#c084fc' },
  { id: 'vampire_goth_body', name: 'Gotik Gövde', description: 'Soluk beyaz skin ve kan kırmızısı gotik detaylar.', cost: 1200, category: 'body', emoji: '🧛', accentColor: '#991b1b' },

  // ── HAIR & HEAD ACCESSORIES (Saçlar & Şapkalar) ── 20 Items
  { id: 'default_hair', name: 'Saçsız', description: 'Klasik pürüzsüz baş.', cost: 0, category: 'hair', emoji: '🥚', accentColor: '#6b7280' },
  { id: 'mohawk_hair', name: 'Punk Saç', description: 'Havalı kırmızı bir mohawk saç stili.', cost: 30, category: 'hair', emoji: '🦹', accentColor: '#ef4444' },
  { id: 'crown_hair', name: 'Kraliyet Tacı', description: 'Kafanın üstünde duran havalı altın bir taç.', cost: 30, category: 'hair', emoji: '👑', accentColor: '#fbbf24' },
  { id: 'cap_hair', name: 'Retro Şapka', description: 'Ters takılmış neon renkli piksel şapka.', cost: 30, category: 'hair', emoji: '🧢', accentColor: '#06b6d4' },
  { id: 'ninja_headband', name: 'Ninja Bandanası', description: 'Kırmızı rüzgarda dalgalanan otantik ninja kafa bandı.', cost: 30, category: 'hair', emoji: '🥷', accentColor: '#dc2626' },
  { id: 'cat_ears', name: 'Kedi Kulakları', description: 'Sevimli pembe piksel kedi kulaklı taç.', cost: 30, category: 'hair', emoji: '🐱', accentColor: '#ec4899' },
  { id: 'viking_helmet', name: 'Viking Kaskı', description: 'İki yanında büyük boynuzları olan çelik miğfer.', cost: 150, category: 'hair', emoji: '🪖', accentColor: '#9ca3af' },
  { id: 'wizard_hat', name: 'Büyücü Şapkası', description: 'Yıldız desenli sivri mor büyücü şapkası.', cost: 150, category: 'hair', emoji: '🧙', accentColor: '#8b5cf6' },
  { id: 'headphones', name: 'RGB Kulaklık', description: 'Neon ışıklı retro oyuncu kulaklığı.', cost: 150, category: 'hair', emoji: '🎧', accentColor: '#06b6d4' },
  { id: 'pirate_hat', name: 'Korsan Kaptanı Şapkası', description: 'Kuru kafa işlemeli süslü üçşapka.', cost: 150, category: 'hair', emoji: '🏴‍☠️', accentColor: '#1e293b' },
  { id: 'chef_hat', name: 'Aşçı Şapkası', description: 'Lezzetli alışkanlıklar için yüksek beyaz şef şapkası.', cost: 150, category: 'hair', emoji: '👨‍🍳', accentColor: '#f8fafc' },
  { id: 'afro_hair', name: 'Afro Saç', description: 'Hacimli retro 70\'ler tarzı kıvırcık afro saç.', cost: 500, category: 'hair', emoji: '💈', accentColor: '#451a03' },
  { id: 'halo_angel', name: 'Melek Halesi', description: 'Kafanın üstünde süzülen parlak sarı kutsal melek halkası.', cost: 500, category: 'hair', emoji: '😇', accentColor: '#fde047' },
  { id: 'detective_hat', name: 'Dedektif Kasketi', description: 'Kahverengi ekose Sherlock kasketi.', cost: 500, category: 'hair', emoji: '🕵️', accentColor: '#78350f' },
  { id: 'flower_wreath', name: 'Bahar Çiçek Tacı', description: 'Rengarenk canlı doğa çiçeklerinden örülmüş taç.', cost: 500, category: 'hair', emoji: '🌸', accentColor: '#f43f5e' },
  { id: 'party_hat', name: 'Parti Külahı', description: 'Renkli puantiyeli doğum günü parti şapkası.', cost: 500, category: 'hair', emoji: '🎉', accentColor: '#eab308' },
  { id: 'cyber_horns', name: 'Siber Boynuzlar', description: 'Işıltılı neon pembe ve siyan siber boynuzlar.', cost: 800, category: 'hair', emoji: '😈', accentColor: '#ec4899' },
  { id: 'top_hat', name: 'Aristokrat Silindir', description: 'Kırmızı şeritli asil silindir şapka.', cost: 800, category: 'hair', emoji: '🎩', accentColor: '#0f172a' },
  { id: 'santa_hat', name: 'Noel Şapkası', description: 'Yumuşak ponponlu kırmızı kutlama şapkası.', cost: 800, category: 'hair', emoji: '🎅', accentColor: '#ef4444' },
  { id: 'valkyrie_wings', name: 'Valkyrie Miğferi', description: 'İki yanında gümüş kanatları olan mitolojik miğfer.', cost: 1200, category: 'hair', emoji: '⚔️', accentColor: '#e2e8f0' },

  // ── EYES (Gözler & Gözlükler) ── 20 Items
  { id: 'default_eyes', name: 'Normal Gözler', description: 'Sıradan piksel gözler.', cost: 0, category: 'eyes', emoji: '👀', accentColor: '#6b7280' },
  { id: 'cool_sunglasses', name: 'Siyah Gözlük', description: 'Havalı piksel güneş gözlüğü. Karizma +100.', cost: 30, category: 'eyes', emoji: '😎', accentColor: '#111827' },
  { id: 'monocle_eyes', name: 'Monokl Gözlük', description: 'Tek gözde duran klasik aristokrat gözlüğü.', cost: 30, category: 'eyes', emoji: '🧐', accentColor: '#b45309' },
  { id: 'virtual_visor', name: 'VR Vizör', description: 'Gelecekten gelen neon pembe siber vizör.', cost: 30, category: 'eyes', emoji: '🕶️', accentColor: '#ec4899' },
  { id: 'anime_sparkle_eyes', name: 'Işıl Işıl Gözler', description: 'Yıldız parıltılı şirin anime gözleri.', cost: 30, category: 'eyes', emoji: '✨', accentColor: '#f43f5e' },
  { id: '3d_glasses', name: '3D Sinema Gözlüğü', description: 'Kırmızı ve mavi camlı retro 3D gözlük.', cost: 30, category: 'eyes', emoji: '👓', accentColor: '#ef4444' },
  { id: 'pirate_eyepatch', name: 'Korsan Bandı', description: 'Gizemli denizciler için klasik siyah korsan göz bandı.', cost: 150, category: 'eyes', emoji: '🏴‍☠️', accentColor: '#1e293b' },
  { id: 'glowing_laser_eyes', name: 'Lazer Gözler', description: 'Gözlerden dışarı saçılan kırmızı lazer ışınları!', cost: 150, category: 'eyes', emoji: '💥', accentColor: '#ef4444' },
  { id: 'heart_eyes', name: 'Aşk Kalpleri', description: 'Gözlerin yerini alan canlı kırmızı aşk kalpleri.', cost: 150, category: 'eyes', emoji: '😍', accentColor: '#f43f5e' },
  { id: 'hypno_spiral', name: 'Hipnoz Spiral', description: 'Büyüleyici yeşil dönen hipnoz gözler.', cost: 150, category: 'eyes', emoji: '🌀', accentColor: '#10b981' },
  { id: 'money_eyes', name: 'Dolar İşaretleri', description: 'Kazanılan Habitium\'larla gözleri dolar basan tasarım!', cost: 150, category: 'eyes', emoji: '🤑', accentColor: '#854d0e' },
  { id: 'star_glasses', name: 'Yıldız Gözlük', description: 'Sarı piksel yıldız şeklinde gözlük camları.', cost: 500, category: 'eyes', emoji: '⭐', accentColor: '#facc15' },
  { id: 'crying_tears', name: 'Duygusal Damlalar', description: 'Sevimli mavi piksel gözyaşı damlaları.', cost: 500, category: 'eyes', emoji: '🥺', accentColor: '#38bdf8' },
  { id: 'pixel_goggles', name: 'Steampunk Gözlük', description: 'Pirinç döküm endüstriyel koruma gözlüğü.', cost: 500, category: 'eyes', emoji: '🥽', accentColor: '#ca8a04' },
  { id: 'cyborg_target_eye', name: 'Siber Hedef Göz', description: 'Kırmızı hedef göstergeli mekanik siber göz.', cost: 500, category: 'eyes', emoji: '🎯', accentColor: '#dc2626' },
  { id: 'cat_eye_glasses', name: 'Kedi Göz Çerçeve', description: 'Retro 50\'ler tarzı siyah kedi gözlük çerçevesi.', cost: 500, category: 'eyes', emoji: '🕶️', accentColor: '#0f172a' },
  { id: 'sleepy_eyes', name: 'Uykulu Çizgiler', description: 'Rahatlamış uykulu piksel göz çizgileri.', cost: 800, category: 'eyes', emoji: '😴', accentColor: '#94a3b8' },
  { id: 'fire_eyes', name: 'Alevli Bakışlar', description: 'Göz yuvalarından çıkan turuncu alev dalgaları.', cost: 800, category: 'eyes', emoji: '🔥', accentColor: '#ea580c' },
  { id: 'diamond_eyes', name: 'Elmas Bakış', description: 'Saf elmas parıltılı kristal göz bebekleri!', cost: 800, category: 'eyes', emoji: '💎', accentColor: '#38bdf8' },
  { id: 'blindfold_master', name: 'Dövüş Ustası Bandı', description: 'Gözleri örten asil beyaz dövüş sanatları kumaşı.', cost: 1200, category: 'eyes', emoji: '🥋', accentColor: '#f8fafc' },

  // ── OUTFITS (Kıyafetler) ── 20 Items
  { id: 'default_outfit', name: 'Çıplak Habitus', description: 'Herhangi bir kıyafeti yok.', cost: 0, category: 'outfit', emoji: '👕', accentColor: '#6b7280' },
  { id: 'casual_hoodie', name: 'Yeşil Kapüşonlu', description: 'Günlük havalı ve çok rahat bir spor kapüşonlu.', cost: 30, category: 'outfit', emoji: '🧥', accentColor: '#10b981' },
  { id: 'retro_suit', name: 'Retro Takım Elbise', description: 'Centilmenler için şık siyah-beyaz piksel takım.', cost: 30, category: 'outfit', emoji: '👔', accentColor: '#1f2937' },
  { id: 'wizard_robe', name: 'Büyücü Cübbesi', description: 'Yıldız desenli mor büyücü kostümü.', cost: 30, category: 'outfit', emoji: '🧙', accentColor: '#8b5cf6' },
  { id: 'astronaut_outfit', name: 'Astronot Giysisi', description: 'Uzay keşifleri için özel astronot tulumu.', cost: 30, category: 'outfit', emoji: '👨‍🚀', accentColor: '#f3f4f6' },
  { id: 'ninja_gi', name: 'Ninja Zırhı', description: 'Kırmızı kuşaklı gizli dövüş sanatçısı giysisi.', cost: 30, category: 'outfit', emoji: '🥋', accentColor: '#1e293b' },
  { id: 'royal_armor', name: 'Şövalye Zırhı', description: 'Altın süslemeli çelik göğüs zırhı.', cost: 150, category: 'outfit', emoji: '🛡️', accentColor: '#9ca3af' },
  { id: 'hawaiian_shirt', name: 'Havai Gömleği', description: 'Palmiye ve çiçek desenli renkli yaz gömleği.', cost: 150, category: 'outfit', emoji: '🌺', accentColor: '#f59e0b' },
  { id: 'superhero_cape', name: 'Kahraman Pelerini', description: 'Sarı amblemli ve kırmızı pelerinli kahraman kostümü.', cost: 150, category: 'outfit', emoji: '🦸', accentColor: '#ef4444' },
  { id: 'kimono_outfit', name: 'Geleneksel Kimono', description: 'Çiçek nakışlı zarif kırmızı kimono.', cost: 150, category: 'outfit', emoji: '👘', accentColor: '#ec4899' },
  { id: 'overalls_worker', name: 'İşçi Tulumu', description: 'Mavi kot pantolon askılı işçi tulumu.', cost: 150, category: 'outfit', emoji: '👖', accentColor: '#2563eb' },
  { id: 'tracksuit_retro', name: '90\'lar Eşofman', description: 'Kırmızı-beyaz nostaljik spor eşofman takımı.', cost: 500, category: 'outfit', emoji: '🏃', accentColor: '#dc2626' },
  { id: 'overcoat_detective', name: 'Trençkot Palto', description: 'Koyu kahverengi şık dedektif pardösüsü.', cost: 500, category: 'outfit', emoji: '🧥', accentColor: '#78350f' },
  { id: 'doctor_coat', name: 'Doktor Önlüğü', description: 'Stetoskop detaylı doktor önlüğü.', cost: 500, category: 'outfit', emoji: '🩺', accentColor: '#ffffff' },
  { id: 'pirate_coat', name: 'Korsan Kaptanı Ceketi', description: 'Altın düğmeli kırmızı süslü korsan ceketi.', cost: 500, category: 'outfit', emoji: '⚓', accentColor: '#b91c1c' },
  { id: 'cyberpunk_jacket', name: 'Siberpunk Deri Ceket', description: 'Yakası neon mavi LED ışıklı siyah deri ceket.', cost: 500, category: 'outfit', emoji: '⚡', accentColor: '#06b6d4' },
  { id: 'pajamas_bear', name: 'Ayıcıklı Pijama', description: 'Düğmeli aşırı sevimli pijama kostümü.', cost: 800, category: 'outfit', emoji: '🧸', accentColor: '#fb7185' },
  { id: 'tuxedo_gold', name: 'Altın Tuxedo', description: 'Şampanya altını ve siyah yaka elit özel dikim damatlık.', cost: 800, category: 'outfit', emoji: '✨', accentColor: '#eab308' },
  { id: 'dino_onesie', name: 'Dinozor Tulumu', description: 'Sırtı dikenli eğlenceli yeşil dinozor tulumu.', cost: 800, category: 'outfit', emoji: '🦖', accentColor: '#16a34a' },
  { id: 'pharaoh_robe', name: 'Firavun Giysisi', description: 'Altın yaka takılı Antik Mısır kraliyet giysisi.', cost: 1200, category: 'outfit', emoji: '🏺', accentColor: '#facc15' },

  // ── HOUSES (Evler / Arka Planlar) ── 20 Items
  { id: 'default_background', name: 'Boş Piksel Oda', description: 'Sıradan, sade gri piksel oda.', cost: 0, category: 'home', emoji: '🧱', accentColor: '#9ca3af' },
  { id: 'retro_arcade', name: 'Arcade Oyun Odası', description: 'Neon atari makineleri ve retro ışıklarla dolu oyuncu odası.', cost: 30, category: 'home', emoji: '🕹️', accentColor: '#f43f5e' },
  { id: 'cyber_penthouse', name: 'Siber Rezidans', description: 'Neon şehir manzaralı siberpunk lüks çatı katı.', cost: 30, category: 'home', emoji: '🏙️', accentColor: '#a855f7' },
  { id: 'nature_cabin', name: 'Doğa Kulübesi', description: 'Şömineli, orman içinde huzurlu ahşap piksel kulübe.', cost: 30, category: 'home', emoji: '🏡', accentColor: '#22c55e' },
  { id: 'space_station', name: 'Uzay İstasyonu', description: 'Pencereden gezegenlerin izlendiği galaktik üs.', cost: 30, category: 'home', emoji: '🚀', accentColor: '#3b82f6' },
  { id: 'beach_sunset', name: 'Gün Batımı Plajı', description: 'Palmiyeler ve turuncu gün batımı deniz manzarası.', cost: 30, category: 'home', emoji: '🌅', accentColor: '#f97316' },
  { id: 'zen_garden', name: 'Zen Bahçesi', description: 'Sakura ağaçlı ve bambulu Japon huzur bahçesi.', cost: 150, category: 'home', emoji: '🌸', accentColor: '#ec4899' },
  { id: 'dungeon_castle', name: 'Şato Zindanı', description: 'Meşaleli, gizemli taş duvarlı orta çağ kalesi.', cost: 150, category: 'home', emoji: '🏰', accentColor: '#475569' },
  { id: 'cozy_library', name: 'Ahşap Kütüphane', description: 'Tavana kadar kitaplıklarla dolu sıcak çalışma odası.', cost: 150, category: 'home', emoji: '📚', accentColor: '#92400e' },
  { id: 'underwater_reef', name: 'Mercan Kayalığı', description: 'Sualtı dünyası ve etrafta yüzen piksel balıklar.', cost: 150, category: 'home', emoji: '🐠', accentColor: '#0284c7' },
  { id: 'volcano_lair', name: 'Magma Mağarası', description: 'Kırmızı lav nehirleri akan volkanik sığınak.', cost: 150, category: 'home', emoji: '🌋', accentColor: '#dc2626' },
  { id: 'candy_kingdom', name: 'Şeker Diyarı', description: 'Pembe bulutlar ve dondurma tepeleri manzaralı krallık.', cost: 500, category: 'home', emoji: '🍭', accentColor: '#f472b6' },
  { id: 'graveyard_spooky', name: 'Hayaletli Mezarlık', description: 'Dolunay ışığında sisli gizemli mezarlık.', cost: 500, category: 'home', emoji: '🪦', accentColor: '#334155' },
  { id: 'disco_dancefloor', name: '80\'ler Disko Salonu', description: 'Renkli karolu dans pisti ve ışık gösterisi.', cost: 500, category: 'home', emoji: '🪩', accentColor: '#eab308' },
  { id: 'cloud_palace', name: 'Bulut Sarayı', description: 'Gökyüzünün üzerinde süzülen altın kubbeli bulut şatosu.', cost: 500, category: 'home', emoji: '☁️', accentColor: '#38bdf8' },
  { id: 'matrix_digital', name: 'Siber Matris Odası', description: 'Dikey yeşil dijital kodların aktığı siber ortam.', cost: 500, category: 'home', emoji: '💻', accentColor: '#10b981' },
  { id: 'desert_pyramids', name: 'Mısır Piramitleri', description: 'Sıcak çöl kumları ve güneş altında piramitler.', cost: 800, category: 'home', emoji: '🏜️', accentColor: '#d97706' },
  { id: 'cyber_ramen_shop', name: 'Siber Ramen Restoranı', description: 'Kırmızı neon fenerli otantik Japon ramen mekanı.', cost: 800, category: 'home', emoji: '🍜', accentColor: '#ef4444' },
  { id: 'snowy_igloo', name: 'Kuzey Kutbu İglo', description: 'Kuzey ışıkları altında huzurlu karlı Eskimo ortamı.', cost: 800, category: 'home', emoji: '🏔️', accentColor: '#bae6fd' },
  { id: 'gold_treasury', name: 'Ejderha Hazine Odası', description: 'Altın sikkeler ve mücevher dağlarıyla dolu krallık kasası.', cost: 1200, category: 'home', emoji: '💰', accentColor: '#eab308' },

  // ── VEHICLES (Arabalar / Araçlar) ── 20 Items
  { id: 'default_none', name: 'Yaya', description: 'Herhangi bir aracı yok, yürüyerek gidiyor.', cost: 0, category: 'vehicle', emoji: '🚶', accentColor: '#6b7280' },
  { id: 'pixel_skateboard', name: 'Piksel Kaykay', description: 'Ateş desenli, sokak tarzı tahta kaykay.', cost: 30, category: 'vehicle', emoji: '🛹', accentColor: '#d97706' },
  { id: 'retro_car', name: 'Retro Spor Araba', description: 'Kırmızı, havalı üstü açık 8-bit spor araba.', cost: 30, category: 'vehicle', emoji: '🏎️', accentColor: '#dc2626' },
  { id: 'hoverboard', name: 'Uçan Kaykay', description: 'Yerden yüksekte uçan mavi siber kaykay.', cost: 30, category: 'vehicle', emoji: '🛸', accentColor: '#2563eb' },
  { id: 'magic_carpet', name: 'Uçan Halı', description: 'Püsküllü ve desenli büyülü oryantal halı.', cost: 30, category: 'vehicle', emoji: '🪔', accentColor: '#a855f7' },
  { id: 'racing_kart', name: 'Yarış Kartı', description: 'Yeşil-siyah mini pist go-kartı.', cost: 30, category: 'vehicle', emoji: '🏎️', accentColor: '#10b981' },
  { id: 'bamboo_raft', name: 'Bambu Sal', description: 'Su üzerinde süzülen otantik bambu sal.', cost: 150, category: 'vehicle', emoji: '🛶', accentColor: '#84cc16' },
  { id: 'mecha_scooter', name: 'Siber Scooter', description: 'Neon ışıklı sarı siber şehir scooter motoru.', cost: 150, category: 'vehicle', emoji: '🛵', accentColor: '#eab308' },
  { id: 'flying_broom', name: 'Büyücü Süpürgesi', description: 'Havada süzülen otantik uçan tahta süpürge.', cost: 150, category: 'vehicle', emoji: '🧹', accentColor: '#b45309' },
  { id: 'giant_mech_foot', name: 'Dev Robot Adımı', description: 'Siber mecha dev robotunun üzerinde seyahat edin!', cost: 150, category: 'vehicle', emoji: '🤖', accentColor: '#475569' },
  { id: 'steam_locomotive', name: 'Buharlı Lokomotif', description: 'Dumanlar çıkaran nostaljik tren makinesi.', cost: 150, category: 'vehicle', emoji: '🚂', accentColor: '#1e293b' },
  { id: 'ufo_saucer', name: 'Uçan Daire UFO', description: 'Altından yeşil ışın saçan uzay gemisi.', cost: 500, category: 'vehicle', emoji: '🛸', accentColor: '#10b981' },
  { id: 'pirate_ship', name: 'Korsan Gemisi', description: 'Topları ve siyah yelkeni olan korsan kalyonu.', cost: 500, category: 'vehicle', emoji: '🏴‍☠️', accentColor: '#78350f' },
  { id: 'bmx_bike', name: 'BMX Sokak Bisikleti', description: 'Sarı çelik kadrolu havalı BMX bisiklet.', cost: 500, category: 'vehicle', emoji: '🚲', accentColor: '#eab308' },
  { id: 'tank_mini', name: 'Mini Askeri Tank', description: 'Paletli yeşil piksel savaş tankı.', cost: 500, category: 'vehicle', emoji: '🪖', accentColor: '#3f6212' },
  { id: 'submersible', name: 'Sarı Denizaltı', description: 'Derin sulara dalan sevimli sarı denizaltı.', cost: 500, category: 'vehicle', emoji: '⚓', accentColor: '#facc15' },
  { id: 'shopping_cart', name: 'Market Arabası', description: 'Eğlenceli metal alışveriş arabası!', cost: 800, category: 'vehicle', emoji: '🛒', accentColor: '#94a3b8' },
  { id: 'golden_chariot', name: 'Altın Savaş Arabası', description: 'Şaşaalı krallara layık imparatorluk at arabası.', cost: 800, category: 'vehicle', emoji: '🐎', accentColor: '#eab308' },
  { id: 'rocket_thruster', name: 'Jet Sırt Roketi', description: 'Sırta takılan alev jetli jetpack roket.', cost: 800, category: 'vehicle', emoji: '🚀', accentColor: '#ef4444' },
  { id: 'cloud_nimbus', name: 'Büyülü Sarı Bulut', description: 'Altında süzülen efsanevi sarı bulut tahtı.', cost: 1200, category: 'vehicle', emoji: '☁️', accentColor: '#fef08a' },

  // ── COMPANIONS (Evcil Hayvanlar / Yoldaşlar) ── 20 Items
  { id: 'companion_none', name: 'Yalnız', description: 'Yoldaşı yok.', cost: 0, category: 'companion', emoji: '👤', accentColor: '#6b7280' },
  { id: 'pixel_cat', name: 'Piksel Kedi', description: 'Habitus\'un yanında uyuklayan minik turuncu pisi.', cost: 30, category: 'companion', emoji: '🐱', accentColor: '#f97316' },
  { id: 'tiny_robot', name: 'Mini Robot', description: 'Havada süzülen, bip-bop sesleri çıkaran sevimli drone.', cost: 30, category: 'companion', emoji: '🤖', accentColor: '#3b82f6' },
  { id: 'tiny_dragon', name: 'Bebek Ejderha', description: 'Minik alev püreleri çıkaran nadir kırmızı ejdercik!', cost: 30, category: 'companion', emoji: '🐉', accentColor: '#ef4444' },
  { id: 'pixel_dog', name: 'Piksel Köpek', description: 'Kulaklarını sallayan sadık turkuaz tasmalı köpek.', cost: 30, category: 'companion', emoji: '🐶', accentColor: '#eab308' },
  { id: 'ghost_pet', name: 'Minik Hayalet', description: 'Havada süzülen sevimli arkadaş canlısı hayalet.', cost: 30, category: 'companion', emoji: '👻', accentColor: '#cbd5e1' },
  { id: 'phoenix_bird', name: 'Anka Kuşu', description: 'Alev kanatlarıyla süzülen efsanevi Anka kuşu.', cost: 150, category: 'companion', emoji: '🔥', accentColor: '#f97316' },
  { id: 'slime_pet', name: 'Zümrüt Slime', description: 'Zıp zıp zıplayan neşeli zümrüt yeşili jöle.', cost: 150, category: 'companion', emoji: '🟢', accentColor: '#10b981' },
  { id: 'baby_penguin', name: 'Minik Penguen', description: 'Kırmızı piksel atkılı tatlı penguen.', cost: 150, category: 'companion', emoji: '🐧', accentColor: '#0284c7' },
  { id: 'owl_wise', name: 'Gece Baykuşu', description: 'Gözlüklü bilge gece baykuşu yoldaş.', cost: 150, category: 'companion', emoji: '🦉', accentColor: '#78350f' },
  { id: 'alien_blob', name: 'Mor Uzaylı Slime', description: 'Tek gözlü süzülen mor uzaylı pet.', cost: 150, category: 'companion', emoji: '👾', accentColor: '#a855f7' },
  { id: 'golden_beetle', name: 'Altın Uğur Böceği', description: 'Şans getiren parlak altın piksel uğur böceği.', cost: 500, category: 'companion', emoji: '🐞', accentColor: '#eab308' },
  { id: 'corgi_pup', name: 'Corgi Yavrusu', description: 'Kısa bacaklı sevimli Corgi köpeği.', cost: 500, category: 'companion', emoji: '🐕', accentColor: '#d97706' },
  { id: 'fox_kitsune', name: 'Mistik Tilki', description: 'Mistik kuyruklarıyla süzülen efsanevi tilki.', cost: 500, category: 'companion', emoji: '🦊', accentColor: '#ea580c' },
  { id: 'panda_mini', name: 'Minik Panda', description: 'Elinde bambusu olan tatlı panda yavrusu.', cost: 500, category: 'companion', emoji: '🐼', accentColor: '#1e293b' },
  { id: 'floating_skull', name: 'Alevli Kuru Kafa', description: 'Mavi alevlerle süzülen mistik kuru kafa.', cost: 500, category: 'companion', emoji: '💀', accentColor: '#06b6d4' },
  { id: 'fairy_pixie', name: 'Işık Perisi', description: 'Kanat çırpan yıldız ışıklı minik peri.', cost: 800, category: 'companion', emoji: '🧚', accentColor: '#f472b6' },
  { id: 'unicorn_foal', name: 'Bebek Unicorn', description: 'Gökkuşağı yeleli minik sevimli tek boynuz.', cost: 800, category: 'companion', emoji: '🦄', accentColor: '#f43f5e' },
  { id: 'bat_cute', name: 'Gece Yarasası', description: 'Geceleri süzülen sevimli minik yarasa.', cost: 800, category: 'companion', emoji: '🦇', accentColor: '#475569' },
  { id: 'golden_goose', name: 'Altın Kaz', description: 'Altın yumurtlayan kraliyet kazı!', cost: 1200, category: 'companion', emoji: '🪿', accentColor: '#facc15' },
];
